### ISSUE TITLE
Cant get this to work.

### ISSUE THREAD

**Issue by spookyxbt** [sbaerlocher/dashing.uptimerobot#1]
Followed the instructions, replaced the "api" section with my uptimerobot api and all i get is a blank box. Any ideas where Im going wrong?

Thanks,

**Comment by spookyxbt** [comment]
I think the issue is down to this plugin using APIv1 which is now discontinued through uptimerobot. Do you have plans to update this to APIv2

**Comment by sbaerlocher** [comment]
I will make the adjustments as soon as possible

**Comment by spookyxbt** [comment]
Thanks mate. Appreciate it.

**Comment by spookyxbt** [comment]
Any update on this please?

**Comment by spookyxbt** [comment]
Created a fork with working APIv2 config.
